version: 0.2

phases:
  install:
    runtime-versions:
        java: openjdk8
  build:
    commands:
      - mvn clean
      - mvn install -DskipTests
artifacts:
  files:
   - '**/*'
   # - 'docker-compose.yml'